language: node_js
node_js:
  - "0.12"

services:
  - memcached

cache:
  directories:
    - node_modules

before_script:
  - NODE_ENV='ci' LOG_LEVEL='info' npm start&

script:
  - npm run test
  - npm run test:acceptance-headless
